### ISSUE TITLE
Delete pattern when vocabulary is deleted

### ISSUE THREAD

**Issue by juampynr** [md-systems/pathauto#108]
Currently, PathautoUnitTest has one failing assertion when deleting a vocabulary because its associated pattern is not being deleted:

![selection_006](https://cloud.githubusercontent.com/assets/108130/12007453/5ac9e648-ac05-11e5-91f1-f1790db23b92.png)

I am debugging `pathauto_entity_delete()` to see how we can match a vocabulary entity with its pattern entity. It looks like I should be able to do it by inspecting the pattern conditions.

**Comment by Berdir** [comment]
The code for this is in pathauto_entity_bundle_delete.

I'm not exactly sure what to do with this. It gets more complicated with the conditions. I guess the logic we need to implement is this:
1. Query for patterns for $entity_type that have a bundle condition with this bundle.
   2a. If it's the only bundle in the condition, delete the pattern.
   2b. If it's not, just remove that and save the pattern.

I haven't written this yet since I wasn't 100% sure if we should even keep it. We don't have the same for languages, for examples, or when an entity type is removed (e.g. when uninstalling a module). Unlike before, it is possible to manually delete those now, so we could say that it's up to the user to do this.

But pull requests are welcome.

**Comment by juampynr** [comment]
> Unlike before, it is possible to manually delete those now, so we could say that it's up to the user to do this.

I have the same feeling: it's a considerable amount of work for something that it is not critical for the module. I prefer to simply remove that assertion and let the site administrator to clean up patterns manually.

**Comment by juampynr** [comment]
Pull request at https://github.com/md-systems/pathauto/pull/109

**Comment by juampynr** [comment]
Closing. https://github.com/md-systems/pathauto/pull/109 got merged in.
