### ISSUE TITLE
Error adding Pattern

### ISSUE THREAD

**Issue by rainer-friederich** [md-systems/pathauto#123]
After installing latest pathauto ( from here ) and latest token version ( from do ) on a clean d8 8.0.2 i get an error adding a pattern.

pattern:
pattern type : content
node type: basic page
pattern: test/[node:nid]
languages: ( tested different combinations )

error:
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "entity_bundle:node" plugin does not exist. in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 57 of core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).

**Comment by Berdir** [comment]
You also need the latest ctools dev version

**Comment by rainer-friederich** [comment]
Okay thanks, works.

Another thing:

if i use this pattern: /[node:field_category]/[node:title]

with field_category is an ER to a taxonomy term.
This works for german ( base language ), but always generates the german term title for all other languages also instead of the translation of the term. 

This is a token problem ?

**Comment by Berdir** [comment]
There _is_ an open token issue: https://www.drupal.org/node/2497247

However, I'd expect it to work anyway, since we always pass around the translation object and it should by default use the correct translation. But maybe something goes wrong somewhere. Do you get this on bulk generation or adding the original translation?

@juampynr very recently added a test for multilingual content and pathauto. We should possibly extend that with a token that uses a configurable field, to have a scenario like this covered in tests.

**Comment by rainer-friederich** [comment]
okay thank you.
Perhaps the problem is the following:
the field_category itself is not translatable, but the term itself is translated.

I'll close this issue here.

**Comment by Berdir** [comment]
Hm, that's interesting. Please test if the patch in the core issue helps then. This _should_ work, we fixed that shortly before the stable release. But yes, pretty sure that's a token issue, so lets continue there.
