### ISSUE TITLE
Enable new dependendencies usch as ctools on update

### ISSUE THREAD

**Issue by rodrigoaguilera** [md-systems/pathauto#125]
I had pathauto installed before the addition of ctools as a dependency and I got an exception on update_8100 asking me to install ctools.

I can solve this by running the config import (that enables ctools) before the update of the database but I feel that is not the right order.
If a module declares a new dependency it should at least try to enable it.

**Comment by Berdir** [comment]
That's somewhat tricky because we'd also have to detect if ctools actually exists in the system. If you didn't have it before, it's likely that it doesn't. The site should function well enough to install it yourself.

Note that pathauto moved to drupal.org, so closing this. You're welcome to open an issue with patch if you think this should be fixed.
