### ISSUE TITLE
using Entity reference as a replacement pattern is not working

### ISSUE THREAD

**Issue by tormedo** [md-systems/pathauto#74]
Hi,

as in D7 when I try to use a replacement pattern like `/foo/[node:filed_the_entity:title]/[node:title]` I get the error that this is a non valid pattern.

Since entity is in core in D8 now, I dont know how to enable this in pathauto. (Also there is this EntityRef section missing in the replacement pattern menu).

**Comment by Berdir** [comment]
Pathauto doesn't define tokens, it just uses them. token.module in 7.x never supported field references like that, only tokens from rules.module did that.

You should however be able to achieve what you want by just using node:field_the_entity as token and configure the token view mode so that it shows the entity label without a link. Anything on top of that (like using a field from a reference currently requires custom code. There are some open issues in the token issue queue to improve this, look there.
