### ISSUE TITLE
Port #1899806

### ISSUE THREAD

**Issue by davereid** [md-systems/pathauto#80]
Empty token value(s) can result in a duplicate slash in the resulting URL alias. Reported via https://www.drupal.org/node/2578285

**Comment by Berdir** [comment]
Hm, confused :)

The issue there didn't actually _test_ it in D8, just reported it there because it was a problem in D6.

The issue you're referencing is tested in the method testCleanAlias(). This method exists in the D8 port as well and is working. So I think we're good here?

In Barcelona, I merged all the changes from d.o 7.x-1.x to our 8.x-1.x branch, the only one that I didn't manage to just merge is https://github.com/md-systems/pathauto/issues/75.

**Comment by davereid** [comment]
Yeah, count me in confused. I think they filed the issue in Pathauto because they were having the problem in D6, and wanted to make sure it was solved in D8. Despite not actually using the D8 version.
